name: "Setup Node Environment"
description: "Set up the build environment for a Node project"

inputs:
  runtime_version:
    description: "The default Node runtime version to run builds on"
    required: false
    default: "20.x"

runs:
  using: "composite"
  steps:
    - name: "checkout"
      uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4.2.2
    - name: "node.js ${{ inputs.runtime_version }}"
      uses: "actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a" # v4.2.0
      with:
        node-version: "${{ inputs.runtime_version }}"
        cache: "yarn"
    - name: "yarn dependencies"
      shell: "bash"
      run: "yarn install --immutable"
