name: "build"

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request:

jobs:
  call-build:
    uses: "nayrid/.github/.github/workflows/shared-publish.yaml@trunk"
    secrets: "inherit"
